
DGS_PURCHASING_DATA_DICT = {
    "Creation Date": "System Date",
    "Purchase Date": "Date of purchase order entered by the user; may be backdated, so creation date is primarily used.",
    "Fiscal Year": "Fiscal year derived from creation date (California fiscal year: July 1 - June 30).",
    "LPA Number": "Leveraged Procurement Agreement (Contract Number). Indicates contract spend if present.",
    "Purchase Order Number": "Purchase order identifier; not unique across departments.",
    "Requisition Number": "Requisition identifier; not unique across departments.",
    "Acquisition Type": "Type of acquisition: Non-IT Goods, Non-IT Services, IT Goods, IT Services.",
    "Sub-Acquisition Type": "Depends on the acquisition type used.",
    "Acquisition Method": "Type of acquisition used to make purchase.",
    "Sub-Acquisition Method": "Depends on the acquisition method used.",
    "Department Name": "Name of purchasing department (normalized field).",
    "Supplier Code": "Supplier code (normalized field).",
    "Supplier Name": "Supplier name as entered during registration with the state.",
    "Supplier Qualifications": "Identifies supplier as SB, SBE, DVBE, NP, or MB; can be multiple categories.",
    "Supplier Zip Code": "Supplier zip code.",
    "CalCard": "Indicates if a State credit card (CalCard) was used (Yes/No).",
    "Item Name": "Name of items being purchased.",
    "Item Description": "Description of items being purchased.",
    "Quantity": "Quantity of items purchased.",
    "Unit Price": "Unit price of items.",
    "Total Price": "Total price of items (excludes taxes and shipping).",
    "Classification Codes": "UNSPSC v14 codes for purchased items; may include multiple codes per purchase order.",
    "Normalized UNSPSC": "First 8 digits of the UNSPSC v14 code representing the purchase order.",
    "Commodity Title": "Commodity title correlated with the 8-digit Normalized UNSPSC.",
    "Class": "Class number correlated with the 8-digit Normalized UNSPSC.",
    "Class Title": "Class title correlated with the 8-digit Normalized UNSPSC.",
    "Family": "Family number correlated with the 8-digit Normalized UNSPSC.",
    "Family Title": "Family title correlated with the 8-digit Normalized UNSPSC.",
    "Segment": "Segment number correlated with the 8-digit Normalized UNSPSC."
}
